<?php

namespace App\Libraries;

class ProductCatalog
{
    /**
     * @return array<int, array<string, mixed>>
     */
    public static function all(): array
    {
        return [
            [
                'slug' => 'serum-antiacne',
                'name' => 'Serum Seborregulador',
                'line' => 'Kalympia',
                'category' => 'Facial / Acne y sebo',
                'price' => '$1,290 MXN',
                'size' => '30 mL',
                'image' => base_url('assets/images/products/serum-antiacne.png'),
                'summary' => 'Serum facial seborregulador con enfoque dermocosmetico para piel mixta, grasa y con tendencia acneica.',
                'description' => 'Ayuda a controlar el exceso de grasa, mejorar la apariencia de los poros y mantener la piel mas equilibrada con una sensacion ligera.',
                'ingredients' => ['Acido nordihidroguaiaretico', 'Acido kojico', 'Bisabolol', 'Pantenol', 'Acido hialuronico', 'Niacinamida'],
                'benefits' => [
                    'Controla el exceso de sebo y mejora la sensacion de limpieza',
                    'Favorece una apariencia de poro mas afinada',
                    'Ayuda a calmar visualmente el enrojecimiento',
                    'Mantiene hidratacion sin sensacion pesada',
                ],
                'usage' => [
                    'Limpiar y secar suavemente el rostro',
                    'Aplicar de 3 a 4 gotas sobre el rostro',
                    'Distribuir con movimientos circulares hasta absorber',
                    'Usar manana y noche',
                ],
                'ideal_for' => ['Piel mixta', 'Piel grasa', 'Tendencia acneica', 'Rutinas de control de brillo'],
                'claim' => 'Equilibra, purifica y protege',
            ],
            [
                'slug' => 'serum-antiedad-peptidos-hidratantes',
                'name' => 'Serum Antiedad Peptidos + Hidratantes',
                'line' => 'Kalympia',
                'category' => 'Facial / Antiedad',
                'price' => '$1,390 MXN',
                'size' => '30 mL',
                'image' => base_url('assets/images/products/serum-antiedad-peptidos-hidratantes.jpeg'),
                'summary' => 'Serum facial antiedad para firmeza, soporte de hidratacion y confort cosmetico diario.',
                'description' => 'Pensado para una rutina premium de cuidado facial que combine sensacion ligera, hidratacion visible y apoyo a la elasticidad.',
                'ingredients' => ['Peptidos', 'Hidratantes de soporte', 'Niacinamida', 'Acido hialuronico'],
                'benefits' => [
                    'Mejora la apariencia de firmeza y elasticidad',
                    'Aporta hidratacion sostenida',
                    'Ayuda a suavizar lineas de expresion',
                    'Refuerza una apariencia descansada y luminosa',
                ],
                'usage' => [
                    'Aplicar sobre rostro limpio',
                    'Usar 2 a 4 gotas en rostro y cuello',
                    'Distribuir hasta absorcion completa',
                    'Integrar a rutina de manana y noche',
                ],
                'ideal_for' => ['Piel normal', 'Piel seca', 'Primeros signos de edad', 'Rutinas de hidratacion avanzada'],
                'claim' => 'Firmeza, hidratacion y confort',
            ],
            [
                'slug' => 'serum-antiedad-instantaneo',
                'name' => 'Serum Antiedad Instantaneo',
                'line' => 'Kalympia',
                'category' => 'Facial / Antiedad',
                'price' => '$1,290 MXN',
                'size' => '30 mL',
                'image' => base_url('assets/images/products/serum-antiedad-instantaneo.jpeg'),
                'summary' => 'Serum facial antiedad de sensacion inmediata para una piel con mejor apariencia y textura mas pulida.',
                'description' => 'Combina una presencia visual premium con una narrativa enfocada en resultados cosmeticos visibles y aplicacion sencilla.',
                'ingredients' => ['Peptidos', 'Hidratantes ligeros', 'Activos de soporte cosmetico'],
                'benefits' => [
                    'Favorece una apariencia mas tersa',
                    'Apoya la luminosidad del rostro',
                    'Mejora el acabado de la piel antes o despues de la rutina',
                    'Aporta sensacion ligera y limpia',
                ],
                'usage' => [
                    'Aplicar sobre rostro limpio',
                    'Usar unas gotas sobre cara y cuello',
                    'Dejar absorber antes de crema o protector',
                    'Integrar manana o noche segun rutina',
                ],
                'ideal_for' => ['Piel opaca', 'Rutinas antiedad', 'Usuarios que buscan textura ligera'],
                'claim' => 'Mejor apariencia desde la primera impresion',
            ],
            [
                'slug' => 'serum-aclarante',
                'name' => 'Serum Facial Aclarante',
                'line' => 'Kalympia',
                'category' => 'Facial / Manchas y luminosidad',
                'price' => '$1,290 MXN',
                'size' => '30 mL',
                'image' => base_url('assets/images/products/serum-aclarante.png'),
                'summary' => 'Serum aclarador para apoyar un tono mas uniforme y una piel visualmente renovada.',
                'description' => 'Enfocado en mejorar la apariencia de manchas, opacidad y tono desigual con una sensacion cosmetica ligera.',
                'ingredients' => ['Niacinamida', 'Activos aclarantes', 'Hidratantes ligeros'],
                'benefits' => [
                    'Ayuda a unificar el tono de la piel',
                    'Favorece mayor luminosidad visual',
                    'Acompana rutinas para manchas y marcas',
                    'Textura ligera de absorcion rapida',
                ],
                'usage' => [
                    'Aplicar sobre piel limpia y seca',
                    'Distribuir uniformemente sobre rostro',
                    'Reforzar con protector solar durante el dia',
                    'Usar de forma constante para mejores resultados',
                ],
                'ideal_for' => ['Tono desigual', 'Marcas post imperfeccion', 'Piel opaca'],
                'claim' => 'Tono mas uniforme y luminoso',
            ],
            [
                'slug' => 'serum-regenerador-hidratante',
                'name' => 'Serum Regenerador e Hidratante',
                'line' => 'Kalympia',
                'category' => 'Facial / Reparacion e hidratacion',
                'price' => '$1,250 MXN',
                'size' => '30 mL',
                'image' => base_url('assets/images/products/serum-regenerador-hidratante.jpeg'),
                'summary' => 'Serum facial pensado para reparar la sensacion de deshidratacion y mejorar el confort diario.',
                'description' => 'Ideal para rutinas que priorizan hidratacion, apoyo a la barrera y una sensacion de piel mas flexible.',
                'ingredients' => ['Acido hialuronico', 'Pantenol', 'Activos regeneradores'],
                'benefits' => [
                    'Aporta hidratacion visible y sostenida',
                    'Mejora la sensacion de suavidad',
                    'Favorece una apariencia descansada',
                    'Complementa rutinas de recuperacion cosmetica',
                ],
                'usage' => [
                    'Aplicar sobre rostro limpio',
                    'Distribuir manana y noche',
                    'Combinar con crema hidratante si se requiere',
                    'Usar continuamente para sostener confort',
                ],
                'ideal_for' => ['Piel seca', 'Piel deshidratada', 'Rutinas de recuperacion'],
                'claim' => 'Hidratacion y sensacion reparadora',
            ],
            [
                'slug' => 'crema-manos',
                'name' => 'Crema Hidratante Reparadora para Manos',
                'line' => 'Daily Body Care',
                'category' => 'Corporal / Manos',
                'price' => '$390 MXN',
                'size' => '75 mL',
                'image' => base_url('assets/images/products/crema-manos.png'),
                'summary' => 'Crema para manos con hidratacion, reparacion y proteccion para uso diario.',
                'description' => 'Formula ligera para manos secas, asperas o expuestas al lavado frecuente, con una sensacion limpia y no grasosa.',
                'ingredients' => ['Pantenol', 'Vitamina E', 'Avena sativa', 'Niacinamida'],
                'benefits' => [
                    'Hidratacion profunda y duradera',
                    'Ayuda a reparar la barrera cutanea',
                    'Protege contra resequedad diaria',
                    'Textura ligera y rapida absorcion',
                ],
                'usage' => [
                    'Aplicar sobre manos limpias y secas',
                    'Masajear hasta completa absorcion',
                    'Reaplicar durante el dia segun necesidad',
                    'Ideal despues de lavar las manos',
                ],
                'ideal_for' => ['Manos secas', 'Uso diario', 'Todo tipo de piel'],
                'claim' => 'Repara, hidrata y protege',
            ],
            [
                'slug' => 'crema-concha-nacar-arroz',
                'name' => 'Crema Concha Nacar + Arroz',
                'line' => 'Body Brightening',
                'category' => 'Corporal / Uniformidad',
                'price' => '$420 MXN',
                'size' => '75 mL',
                'image' => base_url('assets/images/products/crema-concha-nacar-arroz.png'),
                'summary' => 'Crema corporal enfocada en una apariencia mas uniforme y luminosa.',
                'description' => 'Una propuesta cosmetica para zonas con tono desigual que busca suavidad, nutricion y mejor acabado visual.',
                'ingredients' => ['Concha nacar', 'Arroz', 'Emolientes de soporte'],
                'benefits' => [
                    'Favorece una apariencia mas luminosa',
                    'Ayuda a suavizar la textura',
                    'Aporta nutricion ligera a la piel',
                    'Ideal para rutinas corporales de uso frecuente',
                ],
                'usage' => [
                    'Aplicar sobre la zona deseada',
                    'Masajear hasta absorcion',
                    'Usar de manera constante',
                    'Complementar con proteccion solar si se expone al sol',
                ],
                'ideal_for' => ['Tono desigual corporal', 'Cuidado diario', 'Rutinas de luminosidad'],
                'claim' => 'Luminosidad y suavidad corporal',
            ],
            [
                'slug' => 'crema-tatuajes-fem',
                'name' => 'Crema para Tatuajes Fem',
                'line' => 'Tattoo Care',
                'category' => 'Corporal / Tatuajes',
                'price' => '$450 MXN',
                'size' => '75 mL',
                'image' => base_url('assets/images/products/crema-tatuajes-fem.png'),
                'summary' => 'Crema de soporte cosmetico para mantener hidratado y visualmente cuidado el tatuaje.',
                'description' => 'Pensada para ayudar a conservar el confort de la piel tatuada, mejorar la sensacion de hidratacion y mantener el area cuidada.',
                'ingredients' => ['Hidratantes de soporte', 'Emolientes', 'Activos calmantes'],
                'benefits' => [
                    'Ayuda a mantener hidratada la zona tatuada',
                    'Favorece una apariencia cuidada del color',
                    'Mejora la sensacion de suavidad',
                    'Aporta confort en el cuidado diario',
                ],
                'usage' => [
                    'Aplicar sobre piel limpia',
                    'Extender una capa uniforme',
                    'Usar segun necesidad diaria',
                    'Evitar friccion intensa despues de aplicar',
                ],
                'ideal_for' => ['Piel tatuada', 'Rutina de mantenimiento', 'Uso diario'],
                'claim' => 'Cuidado hidratante para tatuajes',
            ],
            [
                'slug' => 'crema-tatuajes-hombre',
                'name' => 'Crema para Tatuajes Hombre',
                'line' => 'Tattoo Care',
                'category' => 'Corporal / Tatuajes',
                'price' => '$450 MXN',
                'size' => '75 mL',
                'image' => base_url('assets/images/products/crema-tatuajes-hombre.png'),
                'summary' => 'Crema para cuidado diario del tatuaje con enfoque en hidratacion y confort de la piel.',
                'description' => 'Ayuda a sostener una rutina corporal enfocada en mantener la piel tatuada con mejor apariencia y sensacion.',
                'ingredients' => ['Hidratantes de soporte', 'Emolientes', 'Activos calmantes'],
                'benefits' => [
                    'Acompana la hidratacion de la piel tatuada',
                    'Mejora la sensacion de suavidad',
                    'Favorece una apariencia cuidada del tatuaje',
                    'Se integra facilmente a la rutina diaria',
                ],
                'usage' => [
                    'Aplicar sobre la zona limpia',
                    'Masajear hasta distribuir completamente',
                    'Usar de forma diaria o segun necesidad',
                    'Mantener la piel hidratada de forma constante',
                ],
                'ideal_for' => ['Piel tatuada', 'Cuidado diario', 'Rutinas corporales'],
                'claim' => 'Soporte cosmetico para piel tatuada',
            ],
            [
                'slug' => 'gel-arnica-botanicos',
                'name' => 'Gel Arnica Botanicos',
                'line' => 'Body Relief',
                'category' => 'Corporal / Bienestar',
                'price' => '$360 MXN',
                'size' => '120 mL',
                'image' => base_url('assets/images/products/gel-arnica-botanicos.png'),
                'summary' => 'Gel corporal botanico con sensacion refrescante para la rutina de bienestar diario.',
                'description' => 'Una propuesta corporal de absorcion rapida enfocada en confort, ligereza y sensacion refrescante.',
                'ingredients' => ['Arnica', 'Botanicos de soporte', 'Vehiculo en gel'],
                'benefits' => [
                    'Sensacion refrescante y ligera',
                    'Absorcion rapida sin residuo pesado',
                    'Acompana rutinas de masaje o bienestar',
                    'Facil aplicacion en piernas, brazos o espalda',
                ],
                'usage' => [
                    'Aplicar sobre la zona deseada',
                    'Masajear hasta absorber',
                    'Usar cuantas veces se requiera',
                    'Evitar contacto con ojos y mucosas',
                ],
                'ideal_for' => ['Rutina corporal', 'Uso posterior a actividad fisica', 'Bienestar diario'],
                'claim' => 'Ligero, botanico y refrescante',
            ],
            [
                'slug' => 'maxmachin-minoxidil-hom',
                'name' => 'Maxmachin Minoxidil 5%',
                'line' => 'Hair Performance',
                'category' => 'Capilar / Densidad',
                'price' => '$590 MXN',
                'size' => '60 mL',
                'image' => base_url('assets/images/products/maxmachin-minoxidil-hom.png'),
                'summary' => 'Serum-crema capilar para fortalecer la apariencia del cabello, barba y bigote.',
                'description' => 'Integra una narrativa intensa y una aplicacion sencilla para rutinas de densidad capilar y vello facial.',
                'ingredients' => ['Minoxidil 5%', 'Extracto de romero', 'Keratina'],
                'benefits' => [
                    'Ayuda a mejorar la apariencia de densidad',
                    'Fortalece visualmente cabello y barba',
                    'Contribuye al cuidado diario del cuero cabelludo',
                    'Textura ligera y sin sensacion grasosa',
                ],
                'usage' => [
                    'Aplicar sobre cuero cabelludo, barba o bigote limpio y seco',
                    'Distribuir con masaje ligero',
                    'No enjuagar',
                    'Usar diariamente segun indicacion del producto',
                ],
                'ideal_for' => ['Hombres', 'Cabello debilitado', 'Barba y bigote', 'Rutinas de densidad'],
                'claim' => 'Fuerza desde la raiz',
            ],
            [
                'slug' => 'kargelix-minoxidil-fem',
                'name' => 'Kargelix Minoxidil Fem',
                'line' => 'Hair Performance',
                'category' => 'Capilar / Densidad',
                'price' => '$590 MXN',
                'size' => '60 mL',
                'image' => base_url('assets/images/products/kargelix-minoxidil-fem.png'),
                'summary' => 'Propuesta capilar de uso cosmetico para fortalecer la apariencia del cabello con enfoque femenino.',
                'description' => 'Aporta una experiencia visual premium y una aplicacion practica para rutinas enfocadas en densidad y apariencia saludable.',
                'ingredients' => ['Minoxidil', 'Activos de soporte capilar', 'Base ligera'],
                'benefits' => [
                    'Apoya la apariencia de densidad capilar',
                    'Se integra a rutinas capilares de uso frecuente',
                    'Textura ligera para aplicacion puntual',
                    'Ayuda a sostener una imagen de cabello mas fuerte',
                ],
                'usage' => [
                    'Aplicar en cuero cabelludo limpio y seco',
                    'Distribuir en la zona deseada',
                    'Masajear con suavidad',
                    'Usar de manera constante',
                ],
                'ideal_for' => ['Cabello con menor densidad', 'Rutinas capilares', 'Uso frecuente'],
                'claim' => 'Soporte cosmetico para densidad visible',
            ],
        ];
    }

    /**
     * @return array<string, mixed>|null
     */
    public static function find(string $slug): ?array
    {
        foreach (self::all() as $product) {
            if ($product['slug'] === $slug) {
                return $product;
            }
        }

        return null;
    }
}
